version: '3.8'
services:
  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    environment:
      CLICKHOUSE_DB: 'analytics'
    ports:
      - 8123:8123
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: 'analytics'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
