blank_issues_enabled: true
contact_links:
  - name: Swetrix Homepage
    url: https://swetrix.com
  - name: Swetrix Contact
    url: https://swetrix.com/contact
    about: You can contact us for any questions or concerns.
