name: Mirror to Gitlab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    name: Mirror to Gitlab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitlab.com/spyoungtech/mirror-action.git'
          GIT_USERNAME: ${{ secrets.GITLAB_MIRROR_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GITLAB_MIRROR_PASSWORD }}
